### ISSUE TITLE
Simplify content of main navigation

### ISSUE THREAD

**Issue by angela-tran** [ThisDallasLife/thisdallaslife.com#113]
**Currently**

The main nav has the following links:

- [DART](https://thisdallaslife.com/tagged/DART)
- [Housing](https://thisdallaslife.com/tagged/Housing)
- [I-345](https://thisdallaslife.com/tagged/I-345)
- [Cycling](https://thisdallaslife.com/tagged/Cycling)
- [Blog](https://thisdallaslife.com/blog)
- [Podcast](https://thisdallaslife.com/podcast)
- [About](https://thisdallaslife.com/about)
- [Media](https://thisdallaslife.com/media)

**Change**

The main nav should have the following links:

- {featured tag}
- Topics (with a menu showing all available tags)
- Archive (previously "Blog")
- Podcast
- About
- Media

The `{featured tag}` is one tag that is manually defined. Clicking the tag will open the corresponding topic page.

**Comment by Hexel** [comment]
Closing because a different approach is being taken with the main nav for DallasUrbanists.com.
